# Generated by Django 4.2.18 on 2025-01-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videoservice", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="id",
        ),
        migrations.AlterField(
            model_name="video",
            name="video_id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
