# Generated by Django 4.2.18 on 2025-01-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videoservice", "0002_remove_video_id_alter_video_video_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="last_accessed",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
