# Generated by Django 4.2.18 on 2025-02-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videoservice", "0003_channel_last_accessed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="title",
            new_name="video_title",
        ),
    ]
